version: '3'
services:
  dragonslayer:
    build: .
    container_name: dragonslayer
    network_mode: "host"
    privileged: true
    volumes:
      - ./conf/client.conf:/prj/script/client.conf
    command: -i ${IFACE} -a 1