version: '3'
services:
  hostapd:
    build: ./hostapd
    container_name: hostapd
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - ./hostapd/conf/hostapd.conf:/etc/hostapd/hostapd.conf
      - ./hostapd/conf/hostapd.eap_user:/etc/hostapd/eap_user.txt
    #command: -dd -K

  dhcpd:
    build: ./dhcpd
    container_name: dhcpd
    restart: unless-stopped
    networks:
      - enterprise
    volumes:
      - ./dhcpd/conf/dhcpd.conf:/etc/dhcp/dhcpd.conf

  employee:
    build: ./employee
    container_name: employee
    networks:
      - enterprise

networks:
  enterprise:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br0enterprise
    ipam:
      config:
        - subnet: 192.168.123.0/24
          gateway: 192.168.123.1
          ip_range: 192.168.123.192/27
